# Generated by Django 4.0.6 on 2022-08-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='Departamento',
            new_name='departamento',
        ),
    ]
