# Generated by Django 4.0.6 on 2022-08-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_rename_departamento_categoria_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='lancameto',
            new_name='lancamento',
        ),
    ]
